In [ ]:
#Importing Libraries
import pandas as pd
import numpy as np


In [ ]:
S_df= pd.read_csv("train.csv") # dataFrame create based on rows and columns
# dataset is loaded 

In [ ]:
S_df

textID  ... sentiment
0      cb774db0d1  ...   neutral
1      549e992a42  ...  negative
2      088c60f138  ...  negative
3      9642c003ef  ...  negative
4      358bd9e861  ...  negative
...           ...  ...       ...
27476  4eac33d1c0  ...  negative
27477  4f4c4fc327  ...  negative
27478  f67aae2310  ...  positive
27479  ed167662a5  ...  positive
27480  6f7127d9d7  ...   neutral

[27481 rows x 4 columns]

In [ ]:
chunk_size = 10000
batch_num = 1
for chunk in pd.read_csv('/content/train.csv',chunksize=chunk_size):
  chunk.to_csv('train' + str(batch_num) + '.csv', index= False) 
  batch_num ++1
      

In [ ]:
S_df= pd.read_csv("train1.csv")

# Removing Missing Value

In [ ]:
print(S_df.isnull().sum())


textID           0
text             0
selected_text    0
sentiment        0
dtype: int64


In [ ]:
S_df.dropna(inplace=True)
print(S_df.isnull().sum())

textID           0
text             0
selected_text    0
sentiment        0
dtype: int64


# Text Data Preprocessing

Before we start with any NLP project we need to pre-process the data to get it all in a consistent format.We need to clean, tokenize and convert our data into a matrix. Let's create a function which will perform the following tasks on the Selected_text columns.
dataset Cleaning step:

    Make text lowercase,
    removes hyperlinks,
    remove punctuation
    removes numbers
    tokenizes
    removes stopwords


In [ ]:
# text preprocessing helper functions 

import re
def clean_text(text):
    '''Make text lowercase, remove text in square brackets,remove links,remove punctuation
    and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text
# sub means substance for substitute 
# '\[.*?\]', '', text)= first input argument = '\[.*?\]' which will be removed, ny the second input argument= '' by blank symbol 
#and 3rd input argument= 'text' which is input text,  that will be preprocessed
#W* is raw text
# clean_text() is a user define function , that will take input urgument and process and 
#return the resulting text based on the methods we call inside the function.



In [ ]:
import nltk
from nltk.corpus import stopwords
print(stopwords.words('english'))

LookupError: ignored

In [ ]:
import nltk
from nltk.corpus import stopwords
def text_preprocessing(text):
    
   # Cleaning and parsing the text.
    
    tokenizer = nltk.tokenize.RegexpTokenizer(r'\w+') # r stands for read and w stands for w
    nopunctuation = clean_text(text)# no punctuation and now its punctuation free text now
    tokenized_text = tokenizer.tokenize(nopunctuation)
    remove_stopwords = [w for w in tokenized_text if w not in stopwords.words('english')]
    combined_text = ' '.join(tokenized_text)
    return combined_text

### Pre-processed selected text columns

In [ ]:
S_df['sentiment'].value_counts()

neutral     3051
positive    2268
negative    2162
Name: sentiment, dtype: int64

In [ ]:
# Applying the cleaning function to both test and training datasets
S_df['clean_text'] = S_df['selected_text'].apply(str).apply(lambda x: text_preprocessing(x))

LookupError: ignored

In [ ]:
S_df.head(n=15)

textID  ... sentiment
0   9e38c183ad  ...   neutral
1   d1c010cd47  ...   neutral
2   03c0b749b5  ...  negative
3   99f4063cf1  ...  positive
4   9d605483af  ...   neutral
5   adede39756  ...   neutral
6   9655b72897  ...   neutral
7   52c7993b04  ...  negative
8   2ed155359e  ...  positive
9   18910017a3  ...   neutral
10  6f0f3669ee  ...   neutral
11  67564814b3  ...  negative
12  55644d8682  ...  positive
13  ddc928067a  ...   neutral
14  ce4f7c4a1c  ...  positive

[15 rows x 4 columns]

# Mapping of Response vector

In [ ]:
# S_df will add a new column with the new equel value of sentiment column
#A column with a name "sentiment_num" will be added which displays the numerical value of column "Sentiment".

S_df['sentiment_num']= S_df.sentiment.map({'positive':1,'neutral':0, 'negative':2})

In [ ]:
S_df

textID                                               text  \
0      cb774db0d1                I`d have responded, if I were going   
1      549e992a42      Sooo SAD I will miss you here in San Diego!!!   
2      088c60f138                          my boss is bullying me...   
3      9642c003ef                     what interview! leave me alone   
4      358bd9e861   Sons of ****, why couldn`t they put them on t...   
...           ...                                                ...   
27476  4eac33d1c0   wish we could come see u on Denver  husband l...   
27477  4f4c4fc327   I`ve wondered about rake to.  The client has ...   
27478  f67aae2310   Yay good for both of you. Enjoy the break - y...   
27479  ed167662a5                         But it was worth it  ****.   
27480  6f7127d9d7     All this flirting going on - The ATG smiles...   

                                           selected_text sentiment  \
0                    I`d have responded, if I were going   neutral   
1                                               Sooo SAD  negative   
2                                            bullying me  negative   
3                                         leave me alone  negative   
4                                          Sons of ****,  negative   
...                                                  ...       ...   
27476                                             d lost  negative   
27477                                      , don`t force  negative   
27478                          Yay good for both of you.  positive   
27479                         But it was worth it  ****.  positive   
27480  All this flirting going on - The ATG smiles. Y...   neutral   

                                              clean_text  sentiment_num  
0                     i d have responded if i were going              0  
1                                               sooo sad              2  
2                                            bullying me              2  
3                                         leave me alone              2  
4                                                sons of              2  
...                                                  ...            ...  
27476                                             d lost              2  
27477                                        don t force              2  
27478                           yay good for both of you              1  
27479                                but it was worth it              1  
27480  all this flirting going on the atg smiles yay ...              0  

[27480 rows x 6 columns]

In [ ]:
X = S_df.clean_text # X denotes feature  of a dataset #Feature Matrix

In [ ]:
y=S_df.sentiment_num # y denotes the label # responce vector
#Feature Matrix has a Respose vector. in our case we denoted Feature metrix as X and response vector as y. 
#X is also independendent variable.
#and the y is dependent variable .



In [ ]:
from sklearn import model_selection
X_train,X_test,y_train,y_test=model_selection.train_test_split(X,y, test_size=0.25)

In [ ]:
X_train,X_test,y_train,y_test=model_selection.train_test_split(X,y, test_size=0.25,random_state=100)
# just to show the use of random_state
#The feature X and its label y will be splitted into 4 parts X_train,X_test,y_train,y_test. 
#model_selection library package inside which train test is getting splitting and train_test_split() is calling.
#random_state is a constant value which holds the randomness
#https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

# Defining Training and Test Data steps 
  #1. Mapping the lebels to numerical Value
    #2. Defining Feature Matric & Response vector
     #3. X and Y shape Examination
        #4.Spitilng into Training and Test Data

In [ ]:
X_train

13231                                         not enjoying
8331     the killers where the best a bit disappointed ...
20331                                                right
9537     oh and i went with my friend to myoh last nigh...
25623                                        noooooooooooo
                               ...                        
12120                                          blessed day
24424                                              worried
14148    okay now that i will not be able to sleep toni...
23321                              that s very nice of him
5641     office hours trying to make my computer feel b...
Name: clean_text, Length: 20610, dtype: object

In [ ]:
X_test

7861               your web url looks good
7192     aha ok i might see you there yano
11724                                 love
4780                      aw what about me
19039    moses and his girlfriend broke up
                       ...                
21432                 hope you mom is okay
11042                                 oops
13178               my radiator boiled out
15083                      i hate you josh
11130                          not wanting
Name: clean_text, Length: 6870, dtype: object

# Feature Extraction


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
#Tf-idf= Term frequency-inverse document frequency
#TF/document frequecy i.e inverse document frequecy
#TF/DF 


#steps for Feature Extraction - 1. Import, 2.Instantiate , 3.Fit , 4. Transform


In [ ]:
vect = TfidfVectorizer(stop_words = 'english') #vect is here to define a veriable for vectorizer
#Instantiating the Vectorizer

In [ ]:
print(vect) 

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)


# Fit

In [ ]:
vect.fit( X_train ) # fitting is called the traing of data

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [ ]:
vocabolary = vect.get_feature_names()

In [ ]:
train_tf_idf = vect.transform(X_train)  # after Fit this step will transforem all the value into neumerical form

In [ ]:
train_tf_idf # this is now in sparse metrix form

<20610x13640 sparse matrix of type '<class 'numpy.float64'>'
	with 72606 stored elements in Compressed Sparse Row format>

In [ ]:
train_d_t_m= train_tf_idf.toarray()                                       #d_t__m= document term matrix

In [ ]:
train_d_t_m

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
train_d_t_m.shape

(20610, 13640)

In [ ]:
# for test data
test_tf_idf=vect.transform(X_test)

In [ ]:
test_d_t_m= test_tf_idf.toarray()                                       #d_t__m= document term matrix

In [ ]:
test_d_t_m  #feature metric

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
train_d_t_m.shape

(20610, 13640)

In [ ]:
test_d_t_m.shape

(6870, 13640)

In [ ]:
#Summary
#In this section, Tf-Idf vectorizer has been used to convert the text data in
#to numerical form. Finally we have matrices for both training and test data
#i.e. train tf_df dtm and test tf_df dtm respectively.

# Naive Bayes Model

In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()

%time classifier.fit(train_d_t_m,y_train)

Wall time: 2.14 s


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
predicNBML = classifier.predict(test_d_t_m )

In [ ]:
predicNBML

array([0, 0, 1, ..., 0, 2, 0], dtype=int64)

# Calculate accuracy

In [ ]:
from sklearn import metrics

In [ ]:
metrics.accuracy_score(y_test,predicNBML )

0.7831149927219796

# Confusion Matrix

In [ ]:
metrics.confusion_matrix(y_test,predicNBML)

array([[2541,  146,  105],
       [ 407, 1667,   46],
       [ 687,   99, 1172]], dtype=int64)

# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression


In [ ]:
clf_logistic= LogisticRegression()

In [ ]:
%time clf_logistic.fit(train_d_t_m, y_train)

Wall time: 1min 2s


C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
Predict_m_log= clf_logistic.predict(test_d_t_m)

In [ ]:
Predict_m_log

array([0, 0, 1, ..., 0, 2, 0], dtype=int64)

# Accuracy

In [ ]:
metrics.accuracy_score(y_test,Predict_m_log)

0.7885007278020378

# Confusion metrix

In [ ]:
metrics.confusion_matrix(y_test,Predict_m_log)

array([[2428,  177,  187],
       [ 343, 1703,   74],
       [ 573,   99, 1286]], dtype=int64)

# Decision Tree Model

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
Dt_Clf_model = DecisionTreeClassifier()

In [ ]:
%time Dt_Clf_model.fit(train_d_t_m, y_train)

Wall time: 18min 6s


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
Dt_predict= Dt_Clf_model.predict(test_d_t_m)

In [ ]:
Dt_predict

array([1, 0, 1, ..., 2, 2, 2], dtype=int64)

# Accuracy

In [ ]:
metrics.accuracy_score(y_test,Dt_predict)

0.7596797671033478

# Confusion Metrics

In [ ]:
metrics.confusion_matrix(y_test,Dt_predict)

array([[2065,  245,  482],
       [ 220, 1686,  214],
       [ 359,  131, 1468]], dtype=int64)